export default [
    {
        "name":"常用类",
        "data":[
            {
                nameSpace:"div",
                title:"层标签 div容器",
                icon:"icon-ceng",
                props:{
                    children:""
                },
                children:[]
            },
            { 
                nameSpace:"text",
                title:"文本 Text",
                icon:"icon-font",
                props:{
                    children:"这是默认文本"
                },
                children:[]
            },
            {
                nameSpace:"img",
                title:"图片 Picture",
                icon:"icon-pic",
                props:{
                    src:"https://gw.alicdn.com/tfs/TB1RzxEGG61gK0jSZFlXXXDKFXa-64-64.png"
                },
                children:[]
            },
            {
                nameSpace:"button",
                title:"按钮",
                icon:"icon-font",
                props:{
                    children:"提交"
                },
                children:[]
            }
        ]
    },
    {
        "name":"表单类",
        "data":[
            {
                nameSpace:"input",
                title:"输入框",
                icon:"icon-font",
                props:{
                    value:""
                },
                children:[]
            },
            { 
                nameSpace:"select",
                title:"选择框",
                icon:"icon-font",
                props:{
                    options:[{label:"名称",value:"name"}]
                },
                children:[]
            },
            {
                nameSpace:"form",
                title:"表单form",
                icon:"icon-ceng",
                props:{
                   
                },
                children:[]
            },
            {
                nameSpace:"formItem",
                title:"表单formItem",
                icon:"icon-ceng",
                props:{
                    label:"字段名"
                },
                children:[]
            }
        ]
    },{
        "name":"列表类",
        "data":[
            {
                nameSpace:"table",
                title:"table容器",
                icon:"icon-ceng",
                props:{
                    children:""
                },
                children:[]
            },
            { 
                nameSpace:"tableColumn",
                title:"table子容器tableColumn",
                icon:"icon-ceng",
                props:{
                    children:"这是默认文本"
                },
                children:[]
            },
            {
                nameSpace:"pagination",
                title:"分页Pagination",
                icon:"icon-ceng",
                props:{
                    pageSize:10,
                    defaultCurrent:1,
                    total:100,
                    showSizeChanger:false
                },
                children:[]
            }
        ]
    }
]